### ISSUE TITLE
Some errors was found

### ISSUE THREAD

**Issue by sm1ck** [dipdup-io/starknet-indexer#24]
Hello. I start using your indexer, so following errors was occured:

- ERR indexer.go:354 > handle block error="0xee45f1c0550af491a26b577939ce7a96185387fd16decab29fe4ec06c77fc4 deploy account: json: null unexpected end of JSON input" module=indexer
- ERR indexer.go:354 > handle block error="0x12c218c9c01c2e5cc1f973af4cacf1669a921708a7fd890f02aa0cc66d0b2da invoke version=0x1: internal: internal: can't find contract abi under proxy: 03c406d8575a8abb9601f2be6298c42940c1aa389a2cc50ce2bebd55e89f929f contract=010649a7e51ebf2593eefcde93a525584701adb88ab078e09d08801d4763739a" module=indexer

And others many. These errors can be fixed by restarting the indexer.
But one error in internal_tx.go on this line: case errors.Is(err, decode.ErrUnknownSelector): cannot be fixed by restart. It is important to note that when an error occurs, the indexer goes into an infinite loop.
Thus the indexer very often gets into infinite loops and sometimes it is fixed, sometimes it is not. Maybe there is a setting to skip problematic transactions?

**Comment by aopoltorzhicky** [comment]
Thank you for your detailed description of the problem. 
I think I know what your problem is. And as far as I remember, I fixed it in the master branch. 
Could you please tell me what version you are using and how you are running the indexer?

**Comment by sm1ck** [comment]
Hi. I used the latest version (master), ran through docker compose as in the readme example.

**Comment by aopoltorzhicky** [comment]
Ok. First of all I'd recommend you to disable cache. You can do it by setting `INDEXER_CACHE_DIR` to empty string in environment file. I think it'll resolve part of errors.
If errors will occur, please, let me know.

**Comment by aopoltorzhicky** [comment]
@sm1ck Do you still have any of the errors described above?

**Comment by sm1ck** [comment]
<img width="1247" alt="error" src="https://github.com/dipdup-io/starknet-indexer/assets/45939749/c3b7aebc-f633-42c9-83c7-a9404b86918f">
I think it still not works. I'm not a go programmer, but I've made some small changes (i skip errors, you can look at code lines on attached image) and use the indexer.

**Comment by aopoltorzhicky** [comment]
Ok. I'll try to reproduce this error locally and think about fix it.

**Comment by aopoltorzhicky** [comment]
@sm1ck unfortunately I can't reproduce the error locally and the error is absent on our server with indexer. I think something went wrong when cache was enable. It looks like your database was index incorrectly due to enabled cache. If decoded data is necessary for you I'd recommend you to re-index full starknet with disabled cache. If it's not important for you I think your changes will be good solution.
